import Head from 'next/head'
import Link from 'next/link'
import { ArrowRight } from 'lucide-react'
import Header from '~/components/Header'
import Footer from '~/components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Get Reply</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-white font-sans text-slate-800 antialiased">
        <div className="flex min-h-screen flex-col">
          <Header />
          <main className="flex-1">
            <section className="container grid items-center justify-center gap-6 pt-6 pb-8 md:pt-10 md:pb-12 lg:pt-16 lg:pb-24">
              <div className="mx-auto flex flex-col items-start gap-4 lg:w-[52rem]">
                <h1 className="text-3xl font-bold leading-[1.1] tracking-tighter sm:text-5xl md:text-6xl">
                  Streamline your email follow-ups with GetReply
                </h1>
                <p className="max-w-[42rem] leading-normal text-slate-700 sm:text-xl sm:leading-8">
                  Say goodbye to the hassle of scheduling and writing follow-up emails. GetReply simplifies the process with one-click scheduling and tailored ultra-polite emails written by Chat GPT.
                </p>
              </div>
              <div className="flex gap-4">
                <Link 
                  href="https://github.com/azorin-studio/get-reply/issues/1" 
                  className="inline-flex items-center align-items rounded-md bg-slate-800 py-3.5 px-5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                >
                  Join the beta
                  <span className="-mr-0.5 ml-2 h-5 w-5"><ArrowRight  /></span>

                </Link>

            </div>
            </section>
            
            <hr className="border-slate-200" />
            
            <section className="container grid justify-center gap-6 py-8 md:py-12 lg:py-24">
              <div className="mx-auto flex flex-col gap-4 md:max-w-[52rem]">
                <h2 className="text-3xl font-bold leading-[1.1] tracking-tighter sm:text-3xl md:text-6xl">
                  How it works
                </h2>
                <p className="max-w-[85%] leading-normal text-slate-700 sm:text-lg sm:leading-7">
                  GetReply is a plugin for Gmail using Chat GPT. GetReply writes short, polite follow-up emails that are automatically sent after 2 and 3 days to ensure you get a response to your outbound emails.
                </p>
              </div>

              <div className="mx-auto flex flex-row gap-24 md:max-w-[52rem]">
                <div className="basis-1/2">
                  You send an email applying for a job.
                </div>
                <div className="basis-1/2">                  
                  <p className="font-bold text-slate-700 sm:text-sm">
                    Subject: Application for Software Engineer Position
                  </p>
                  <p className="mt-4 text-slate-700 sm:text-sm">
                    Dear [Hiring Manager&apos;s Name],
                  </p>
                  <p className="mt-4 leading-normal text-slate-700 sm:text-sm">
                    I&apos;m interested in the Software Engineer position at your company. As a software developer with [Number of years] years of experience, I believe I&apos;d be a great fit for the role.
                  </p>
                  <p className="mt-2 text-slate-700 sm:text-sm">
                    Attached is my resume and cover letter for your review. Please let me know if you have any questions.
                  </p>
                  <p className="mt-4 leading-normal text-slate-700 sm:text-sm">
                    Best regards,
                  </p>
                  <p className="leading-normal text-slate-700 sm:text-sm">
                    [Your Name]
                  </p>
                </div>
              </div>

              <div className="mx-auto mt-8 flex flex-row gap-24 md:max-w-[52rem]">
                <div className="basis-1/2">
                  2 days later: GetReply will send an automatic email tailored to your previous exchange.
                </div>
                <div className="basis-1/2">                  
                  {/* <p className="font-bold text-slate-700 sm:text-sm">
                    Subject: Application for Software Engineer Position
                  </p> */}
                  <p className=" text-slate-700 sm:text-sm">
                    Dear [Hiring Manager&apos;s Name],
                  </p>
                  <p className="mt-4 leading-normal text-slate-700 sm:text-sm">
                  Just wanted to check in on my application for the Software Engineer position. Let me know if you need anything else from me.
                  </p>
                  <p className="mt-4 leading-normal text-slate-700 sm:text-sm">
                    Best regards,
                  </p>
                  <p className="leading-normal text-slate-700 sm:text-sm">
                    [Your Name]
                  </p>
                </div>
              </div>

              <div className="mx-auto mt-8 flex flex-row gap-24 md:max-w-[52rem]">
                <div className="basis-1/2">
                  3 days later: GetReply will send one last email to optimise your chances of a response.
                </div>
                <div className="basis-1/2">                  
                  {/* <p className="font-bold text-slate-700 sm:text-sm">
                    Subject: Application for Software Engineer Position
                  </p> */}
                  <p className=" text-slate-700 sm:text-sm">
                    Dear [Hiring Manager&apos;s Name],
                  </p>
                  <p className="mt-4 leading-normal text-slate-700 sm:text-sm">
                  I'm still interested in the Software Engineer position and wanted to follow up on my application. Let me know if you have any questions or if there is anything else I can provide.
                  </p>
                  <p className="mt-4 leading-normal text-slate-700 sm:text-sm">
                    Best regards,
                  </p>
                  <p className="leading-normal text-slate-700 sm:text-sm">
                    [Your Name]
                  </p>
                </div>
              </div>

              <div className="mx-auto flex flex-col mt-12 gap-4 md:max-w-[52rem]">
                <h2 className="text-xl font-bold leading-[1.1] tracking-tighter sm:text-xl md:text-2xl">
                  Say goodbye to generic follow ups.
                </h2>
                <p className="max-w-[85%] leading-normal text-slate-700 sm:text-lg sm:leading-7">
                  Using Chat GPT, GetReply writes follow ups tailored to your exchange, so the text is context aware, meaning more responses.
                </p>
              </div>

            </section>

            <hr className="border-slate-200" />

            <section className="container grid justify-center gap-6 py-8 md:py-12 lg:py-24">
              <div className="mx-auto flex flex-col gap-4 md:max-w-[52rem]">
                <h2 className="text-3xl font-bold leading-[1.1] tracking-tighter sm:text-3xl md:text-6xl">
                  Who is it for?
                </h2>
                <h3 className="text-xl font-bold leading-[1.1] tracking-tighter sm:text-xl md:text-xl">
                  Sales follow-ups
                </h3>
                <p className="max-w-[85%] leading-normal text-slate-700 sm:text-lg sm:leading-7">
                  You&apos;ve sent out a proposal to a potential client and haven&apos;t heard back. Rather than spend time crafting a follow-up email, simply click the GetReply button and let the plugin do the work for you. The polite and professional follow-up emails are automatically sent after 2 and 3 days, increasing the chances of getting a response.
                </p>
                <h3 className="text-xl font-bold leading-[1.1] tracking-tighter sm:text-xl md:text-xl">
                  Networking
                </h3>
                <p className="max-w-[85%] leading-normal text-slate-700 sm:text-lg sm:leading-7">
                  After attending a conference or event, you&apos;ve collected a stack of business cards and want to follow up with each person. Instead of manually sending out individual follow-up emails, use GetReply to schedule and send polite follow-ups with just one click.
                </p>
                <h3 className="text-xl font-bold leading-[1.1] tracking-tighter sm:text-xl md:text-xl">
                  Job hunting
                </h3>
                <p className="max-w-[85%] leading-normal text-slate-700 sm:text-lg sm:leading-7">
                  You&apos;ve sent out multiple job applications but haven&apos;t received any responses. Use GetReply to send polite follow-ups and increase your chances of getting a response from potential employers.
                </p>
                <h3 className="text-xl font-bold leading-[1.1] tracking-tighter sm:text-xl md:text-xl">
                  Customer service
                </h3>
                <p className="max-w-[85%] leading-normal text-slate-700 sm:text-lg sm:leading-7">
                  As a customer service representative, you&apos;ve received a high volume of emails that need follow-up. Use GetReply to quickly and easily schedule polite follow-ups for each email, ensuring that each customer receives a timely response.
                </p>
                <h3 className="text-xl font-bold leading-[1.1] tracking-tighter sm:text-xl md:text-xl">
                  Fundraising
                </h3>
                <p className="max-w-[85%] leading-normal text-slate-700 sm:text-lg sm:leading-7">
                  As a founder you send out a bunch of emails to prospective investors, it can be stressful to keep track of follow ups. Use GetReply to automatically schedule tailored follow ups to make sure you get as many meetings as possible.
                </p>
              </div>
            </section>

            <hr className="border-slate-200" />

            <section className="container grid justify-center gap-6 py-8 md:py-12 lg:py-24">
              <div className="mx-auto flex flex-col gap-4 md:max-w-[52rem]">
                <h2 className="text-3xl font-bold leading-[1.1] tracking-tighter sm:text-3xl md:text-6xl">
                  Frequently asked questions
                </h2>
                <h3 className="mt-8 text-xl font-bold leading-[1.1] tracking-tighter sm:text-xl md:text-xl">
                  Whats the stage of the product?
                </h3>
                <p className="max-w-[85%] leading-normal text-slate-700 sm:text-lg sm:leading-7">
                  It&apos;s just an idea for now, but we intend to start building after we gather a few motivated beta testers.
                </p>
                <h3 className="text-xl font-bold leading-[1.1] tracking-tighter sm:text-xl md:text-xl">
                  How much will you charge?
                </h3>
                <p className="max-w-[85%] leading-normal text-slate-700 sm:text-lg sm:leading-7">
                  We are thinking $5 per month per user.
                </p>
                <h3 className="text-xl font-bold leading-[1.1] tracking-tighter sm:text-xl md:text-xl">
                  Can I self host?
                </h3>
                <p className="max-w-[85%] leading-normal text-slate-700 sm:text-lg sm:leading-7">
                  Yes we will release everything open source, so you can self host for free, or pay $5 per month to use our hosted service.
                </p>
                <h3 className="text-xl font-bold leading-[1.1] tracking-tighter sm:text-xl md:text-xl">
                  Whose behind GetReply?
                </h3>
                <p className="max-w-[85%] leading-normal text-slate-700 sm:text-lg sm:leading-7">
                  <a href="https://azorin.studios">Azorin Studios</a>, we are a small product studio based in Valencia, Spain.
                </p>
              </div>
            </section>

            <hr className="border-slate-200" />

            <section className="container grid justify-center gap-6 py-8 md:py-12 lg:py-24">
              <div className="mx-auto flex flex-col gap-4 md:max-w-[52rem]">
                <h2 className="text-3xl font-bold leading-[1.1] tracking-tighter sm:text-3xl md:text-6xl">
                  Proudly Open Source
                </h2>
                <p className="max-w-[85%] leading-normal text-slate-700 sm:text-lg sm:leading-7">
                  GetReply is open source and powered by open source software. The
                  code will be available on{" "}
                  <Link
                    href='https://github.com/azorin-studio/get-reply'
                    target="_blank"
                    rel="noreferrer"
                    className="underline underline-offset-4"
                  >
                    GitHub
                  </Link>
                  .
                </p>
              </div>
            </section>
          </main>
          <Footer/>
        </div>
      </div>
    </>
  )
}
