import Head from 'next/head'
import Header from '~/components/Header'
import Footer from '~/components/Footer'
import terms from '~/data/terms'

export default function Home() {

  return (
    <>
      <Head>
        <title>Get Reply - Terms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-white font-sans text-slate-800 antialiased">
        <div className="flex min-h-screen flex-col">
          <Header />
          <main className="flex-1 px-4 lg:px=2">
            <section className="container grid items-center justify-center gap-6 pt-6 pb-8 md:pt-10 md:pb-12 lg:pt-16 lg:pb-24">
              <div className="mx-auto flex flex-col items-start gap-4 lg:w-[52rem]">
                <h1 className="text-3xl font-bold leading-[1.1] tracking-tighter sm:text-5xl md:text-6xl">
                  Terms
                </h1>
                <div className="p-2 prose prose-sm whitespace-pre-wrap">
                  {terms}
                </div>
              </div>
            </section>
            

          </main>
          <Footer/>
        </div>
      </div>
    </>
  )
}
