import Head from 'next/head'
import Header from '~/components/Header'
import Footer from '~/components/Footer'

const policy = `
Privacy Policy:
We take your privacy seriously and are committed to protecting your personal information. This policy explains how we collect, use, and share your information.

Information Collection:
We collect the email addresses entered into our demo website. We may also collect analytics data on how our website is being used, such as which pages are being visited and for how long.

Information Use:
We use the email addresses entered into our demo website to generate follow-up emails for demonstration purposes only. We may also use the analytics data to improve our website and services.

Information Sharing:
We do not share or sell any personal information collected through our demo website.

Security:
We take appropriate measures to protect your personal information, but please note that no data transmission over the internet can be guaranteed to be 100% secure.

Changes to This Policy:
We may update this policy from time to time, and any changes will be posted on this page.

Contact:
If you have any questions or concerns about this policy, please contact us at on our Github.
`

export default function PrivacyPage() {
  return (
    <>
      <Head>
        <title>Get Reply - Privacy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-white font-sans text-slate-800 antialiased">
        <div className="flex min-h-screen flex-col">
          <Header />
          <main className="flex-1 px-4 lg:px=2">
            <section className="container grid items-center justify-center gap-6 pt-6 pb-8 md:pt-10 md:pb-12 lg:pt-16 lg:pb-24">
              <div className="mx-auto flex flex-col items-start gap-4 lg:w-[52rem]">
                <h1 className="text-3xl font-bold leading-[1.1] tracking-tighter sm:text-5xl md:text-6xl">
                  Privacy Policy
                </h1>
                <div className="p-2 prose prose-sm whitespace-pre-wrap">
                  {policy}
                </div>
              </div>
            </section>
            

          </main>
          <Footer/>
        </div>
      </div>
    </>
  )
}
